name: CI

on:
   workflow_dispatch:

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install curl grep

       - name: Build root variant
         run: nonroot=0 sh -c "$(curl https://raw.githubusercontent.com/XDream8/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(root)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-root
           path: revanced-*-root.apk

       - name: Build non-root variant
         run: |
          sh -c "$(curl https://raw.githubusercontent.com/XDream8/revanced-creator/main/patch.sh)"
          curl -OL https://github.com/XDream8/revanced-creator/releases/download/v0.1/vanced-microg.apk

       - name: Upload Build Artifact(non-root)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-non-root
           path: |
            revanced-*-non-root.apk
            vanced-microg.apk
